### ISSUE TITLE
Some Bugs In Windows

### ISSUE THREAD

**Issue by siskinc** [baliance/gooxml#138] opened 2017-12-16 16:30 UTC
## Description
  Hi,author.
  First of all,I love this lib,and my english is not good.If I used the wrong words, please forgive me.
  When I watching your example, I was so exciting.But after I run your example's code.The worry is appear.Open the generate file，the windows tell me, can open this file.
## Actual Behavior

Please include a reproducible code snippet or document attachment that
demonstrates the issue.

**Comment by tbaliance** [comment] 2017-12-16 16:31
Which example generates a file that fails to open on Windows?

**Comment by siskinc** [comment] 2017-12-20 15:56
tables,toc,use-template
I just used these example
I feel part of document could have a bug

**Comment by tbaliance** [comment] 2017-12-27 22:27
@siskinc What version of Word are you using?

**Comment by treylav** [comment] 2018-01-08 09:47
I used [simple example](https://github.com/baliance/gooxml/blob/master/_examples/document/simple/main.go) and "Hello, world" from [homepage](https://baliance.com/gooxml/).

When I try to open a file in Word, I get the error "We're sorry. We can't open simple_before.docx because we found a problem with its contents". If I try to open a file in LibreOffice 5 it will open without errors. If I save the file in LibreOffice in docx format, Word will also open it. However, [the online version of Word](https://office.live.com/start/Word.aspx) successfully opens the original file.

- Windows 10 x64 (build 15063.786);
- Word 2016 (build 16.0.8730.2165);
- go 1.9.2;
- gooxml from repo (0.4.0 in version.go).

Generated files before and after save in LibreOffice: [simple_before.docx](https://github.com/baliance/gooxml/files/1611037/simple_before.docx), [simple_after.docx](https://github.com/baliance/gooxml/files/1611036/simple_after.docx).

**Comment by tbaliance** [comment] 2018-01-09 01:40
@treylav Looking into it, but it may take a while.  It works on Word 365 for OSX, Word 2013, and Word 2016 of a slightly older build (16.0.5xxx).  I need to test with a version of Word it fails on.

**Comment by tbaliance** [comment] 2018-01-12 13:54
I installed the latest Word on Windows 10 that comes with Office 365 (Version 1711 Build 8730.2165), which I assume is the same as yours and it can open the file with no errors.

Do you use an English language configured Office, or another language?  Perhaps that's the issue?

**Comment by tbaliance** [comment] 2018-01-12 14:18
@treylav / @siskinc  Can you open each of these files and see if any of them open without error?  

They are each a copy of simple_before.docx with a single file replaced from simple_after.docx.  If one of these works, it will narrow down where the problem is.  They all work correctly on my copy of Word 2016 (as does the original unmodified file).

[simple_content_type.docx](https://github.com/baliance/gooxml/files/1626280/simple_content_type.docx)
[simple_document.docx](https://github.com/baliance/gooxml/files/1626281/simple_document.docx)
[simple_styles.docx](https://github.com/baliance/gooxml/files/1626282/simple_styles.docx)
[simple_numbering.docx](https://github.com/baliance/gooxml/files/1626283/simple_numbering.docx)
[simple_settings.docx](https://github.com/baliance/gooxml/files/1626284/simple_settings.docx)

**Comment by treylav** [comment] 2018-01-16 08:03
Unfortunately, nothing has changed.
I use English as main language in Word and Windows, but Russian as region in system. The system has English, Russian and Korean locale (it's my fault that I did not mention it earlier).
![image](https://user-images.githubusercontent.com/617704/34977748-c97998e8-faac-11e7-86a6-6300375b6e01.png)

**Comment by tbaliance** [comment] 2018-01-16 13:41
@treylav  Were you able to open any of the simple_content_type, simple_document, etc. without issue?

**Comment by tbaliance** [comment] 2018-01-18 16:34
@treylav Try this one, it's simple.docx plus a core properties with a language specified. 

[simple_lang.docx](https://github.com/baliance/gooxml/files/1643628/simple_lang.docx)

**Comment by treylav** [comment] 2018-01-19 07:05
@tbaliance, unfortunately, the situation is the same:
![image](https://user-images.githubusercontent.com/617704/35138504-ec834690-fcff-11e7-9d42-7235fc920536.png)

**Comment by wanton7** [comment] 2018-06-29 16:22
We had similar issue in our software that was created using C#. We used MemoryStream's GetBuffer when we should have used ToArray. This caused files that we saved to get extra zero bytes to end of file. For most people these files worked just fine but some people who tried to open these docx files got "The file is corrupt and cannot be opened" error.

**Comment by tbaliance** [comment] 2018-09-12 01:29
Should be resolved in 1.11, please re-open if you experience any more issues.

**Comment by tbaliance** [comment] 2018-12-24 15:41
Closing this for now, I haven't been able to reproduce it on multiple versions of Word.

**Closed by tbaliance** 2018-12-24 15:41 UTC
